"""In-memory seed data. Replace with database queries when the OLTP layer is wired up."""

ITEMS: list[dict] = [
    {
        "item_id": "c1",
        "title": "Свеча восковая церковная",
        "description": "Натуральный воск, для домашней молитвы.",
        "category": "candle",
        "price": 1.5,
        "stock_quantity": 200,
        "image_url": None,
        "is_available": True,
    },
    {
        "item_id": "c2",
        "title": "Свеча алтарная большая",
        "description": "Длительное горение, чистый воск.",
        "category": "candle",
        "price": 6.0,
        "stock_quantity": 80,
        "image_url": None,
        "is_available": True,
    },
    {
        "item_id": "i1",
        "title": "Икона Спасителя",
        "description": "Освящённая икона на дереве.",
        "category": "icon",
        "price": 25.0,
        "stock_quantity": 10,
        "image_url": None,
        "is_available": True,
    },
    {
        "item_id": "i2",
        "title": "Икона Божией Матери",
        "description": "Освящённая икона на дереве.",
        "category": "icon",
        "price": 28.0,
        "stock_quantity": 8,
        "image_url": None,
        "is_available": True,
    },
    {
        "item_id": "a1",
        "title": "Афонский ладан",
        "description": "Благоухающий ладан с Афона, 50 г.",
        "category": "incense",
        "price": 12.0,
        "stock_quantity": 40,
        "image_url": None,
        "is_available": True,
    },
    {
        "item_id": "p1",
        "title": "Просфора",
        "description": "Свежая просфора для поминовения.",
        "category": "prosphora",
        "price": 2.0,
        "stock_quantity": 0,
        "image_url": None,
        "is_available": False,
    },
]
